//! Generates `circuits/lib/src/repo_vectors.nr`: witness data for the repo
//! open circuit tests (repo_test.nr) — real Merkle paths over BOTH trees and
//! real bilateral Grumpkin Schnorr signatures.
//!
//! Regenerate: `cargo run -p harness -- noir-repo-vectors` (deterministic).

use crate::batch::{tx_message, DepositRequest, SignedTx};
use crate::keys::{sign_with_nonce, Keypair, Signature};
use crate::poseidon::{to_hex, Fr, Hasher, FR_ZERO};
use crate::repo::{
    build_repo_batch, open_message, pos_leaf, L2State, OpenEntry, OpenRequest, Position, PosTree,
};
use crate::tree::{Account, Asset, DEPTH};
use ark_grumpkin::Fr as Scalar;
use std::fmt::Write as _;

fn sibs(s: &[Fr; DEPTH]) -> String {
    let inner: Vec<String> = s.iter().map(to_hex).collect();
    format!("[{}]", inner.join(", "))
}

fn sig_lit(sig: &Signature) -> String {
    let (lo, hi) = sig.s_limbs();
    format!(
        "Signature {{ r_x: {}, r_y: {}, s_lo: {}, s_hi: {} }}",
        to_hex(&sig.r_x),
        to_hex(&sig.r_y),
        to_hex(&lo),
        to_hex(&hi)
    )
}

fn open_lit(o: &OpenEntry) -> String {
    format!(
        "OpenWitness {{\n        borrower_pk_x: {}, borrower_pk_y: {}, borrower_index: {}, borrower_cash: {}, borrower_coll: {}, borrower_nonce: {},\n        borrower_siblings: {},\n        lender_pk_x: {}, lender_pk_y: {}, lender_index: {}, lender_cash: {}, lender_coll: {}, lender_nonce: {},\n        lender_siblings: {},\n        cash: {}, coll: {}, rate_bps: {}, haircut_bps: {}, open_ts: {}, maturity_ts: {},\n        pos_index: {}, pos_old_leaf: {},\n        pos_siblings: {},\n        borrower_sig: {},\n        lender_sig: {},\n        is_active: {},\n    }}",
        to_hex(&o.borrower_pk_x), to_hex(&o.borrower_pk_y), o.borrower_index, o.borrower_cash, o.borrower_coll, o.borrower_nonce,
        sibs(&o.borrower_siblings),
        to_hex(&o.lender_pk_x), to_hex(&o.lender_pk_y), o.lender_index, o.lender_cash, o.lender_coll, o.lender_nonce,
        sibs(&o.lender_siblings),
        o.cash, o.coll, o.rate_bps, o.haircut_bps, o.open_ts, o.maturity_ts,
        o.pos_index, to_hex(&o.pos_old_leaf),
        sibs(&o.pos_siblings),
        sig_lit(&o.borrower_sig), sig_lit(&o.lender_sig),
        o.is_active as u8
    )
}

/// Standard bilateral pair: alice (sk=101) lends cash, bob (sk=202) borrows
/// against coll. Terms per PLAN's flavor: 4.30% (430 bps), 2% haircut.
fn parties() -> (Keypair, Keypair) {
    (Keypair::from_sk(Scalar::from(101u64)), Keypair::from_sk(Scalar::from(202u64)))
}

fn demo_position(borrower: &Keypair, lender: &Keypair) -> Position {
    Position {
        borrower_pk_x: borrower.pk_x(),
        lender_pk_x: lender.pk_x(),
        cash: 1_000_000,
        coll: 3_000_000,
        rate_bps: 430,
        haircut_bps: 200,
        open_ts: 1_700_000_000,
        maturity_ts: 1_700_000_000 + 86_400,
    }
}

fn signed_open(
    hasher: &Hasher,
    p: &Position,
    borrower: &Keypair,
    lender: &Keypair,
    b_nonce: u64,
    l_nonce: u64,
    kb: u64,
    kl: u64,
) -> OpenRequest {
    let msg = open_message(hasher, p, b_nonce, l_nonce);
    OpenRequest {
        position: p.clone(),
        borrower_pk_y: borrower.pk_y(),
        lender_pk_y: lender.pk_y(),
        borrower_nonce: b_nonce,
        lender_nonce: l_nonce,
        borrower_sig: sign_with_nonce(hasher, borrower, msg, Scalar::from(kb)),
        lender_sig: sign_with_nonce(hasher, lender, msg, Scalar::from(kl)),
    }
}

pub fn emit() -> String {
    let hasher = Hasher::new();
    let mut out = String::new();
    let (lender, borrower) = parties(); // alice lends, bob borrows

    writeln!(out, "// GENERATED by `cargo run -p harness -- noir-repo-vectors` - DO NOT EDIT.").unwrap();
    writeln!(out, "// Repo-open witness fixtures for repo_test.nr; bilateral signatures and").unwrap();
    writeln!(out, "// two-tree Merkle paths come from the harness (vector-gated).").unwrap();
    writeln!(out, "use crate::repo::OpenWitness;").unwrap();
    writeln!(out, "use crate::schnorr::Signature;").unwrap();
    writeln!(out, "use crate::tx::{{DepositWitness, TxWitness}};\n").unwrap();

    // --- Scenario R: full batch_repo<2,1,2> over a fresh state ---
    // deposits: lender 10_000_000 cash, borrower 5_000_000 coll;
    // open: 1_000_000 cash vs 3_000_000 coll @430bps, 2% haircut, 1 day;
    // payments: lender -> borrower 250_000 cash (nonce 1, post-open),
    //           borrower coll withdrawal 100_000 (nonce 1, post-open).
    {
        let mut state = L2State::new();
        let deposits = vec![
            DepositRequest { pk_x: lender.pk_x(), asset: Asset::Cash, amount: 10_000_000 },
            DepositRequest { pk_x: borrower.pk_x(), asset: Asset::Coll, amount: 5_000_000 },
        ];
        let p = demo_position(&borrower, &lender);
        let open = signed_open(&hasher, &p, &borrower, &lender, 0, 0, 2101, 2102);
        let wd_field = crate::poseidon::fr_from_u64(770_007);
        let txs = vec![
            {
                let msg = tx_message(&hasher, lender.pk_x(), borrower.pk_x(), Asset::Cash, 250_000, 1, false);
                SignedTx {
                    from_pk_x: lender.pk_x(),
                    from_pk_y: lender.pk_y(),
                    to_field: borrower.pk_x(),
                    asset: Asset::Cash,
                    amount: 250_000,
                    nonce: 1,
                    is_withdraw: false,
                    sig: sign_with_nonce(&hasher, &lender, msg, Scalar::from(2103u64)),
                }
            },
            {
                let msg = tx_message(&hasher, borrower.pk_x(), wd_field, Asset::Coll, 100_000, 1, true);
                SignedTx {
                    from_pk_x: borrower.pk_x(),
                    from_pk_y: borrower.pk_y(),
                    to_field: wd_field,
                    asset: Asset::Coll,
                    amount: 100_000,
                    nonce: 1,
                    is_withdraw: true,
                    sig: sign_with_nonce(&hasher, &borrower, msg, Scalar::from(2104u64)),
                }
            },
        ];
        let w = build_repo_batch(
            &hasher, &mut state, 2, 1, 2, &deposits, &[open], &txs, 1_700_000_100, 250_000_0,
        )
        .expect("scenario R must build");

        writeln!(out, "/// Scenario R: deposits (lender cash, borrower coll), one bilateral open,").unwrap();
        writeln!(out, "/// then a cash transfer + coll withdrawal. Returns the 7 public inputs,").unwrap();
        writeln!(out, "/// the private root openings, then the witness arrays.").unwrap();
        writeln!(
            out,
            "pub fn batch_r() -> ([Field; 7], [Field; 2], [DepositWitness; 2], [OpenWitness; 1], [TxWitness; 2]) {{\n    let pis = [{}, {}, {}, {}, {}, {}, {}];\n    let roots = [{}, {}];",
            to_hex(&w.old_state_root),
            to_hex(&w.new_state_root),
            to_hex(&w.deposit_hash),
            to_hex(&w.withdraw_hash),
            to_hex(&w.da_commitment),
            w.batch_ts,
            w.price,
            to_hex(&w.old_acct_root),
            to_hex(&w.old_pos_root),
        )
        .unwrap();
        let deps: Vec<String> = w
            .deposits
            .iter()
            .map(|d| {
                format!(
                    "DepositWitness {{\n        pk_x: {}, asset: {}, amount: {}, index: {}, old_pk_x: {}, old_cash: {}, old_coll: {}, old_nonce: {},\n        siblings: {},\n        is_active: {},\n    }}",
                    to_hex(&d.pk_x), d.asset as u32, d.amount, d.index, to_hex(&d.old_pk_x), d.old_cash, d.old_coll, d.old_nonce, sibs(&d.siblings), d.is_active as u8
                )
            })
            .collect();
        writeln!(out, "    let deps = [{}];", deps.join(", ")).unwrap();
        let opens: Vec<String> = w.opens.iter().map(open_lit).collect();
        writeln!(out, "    let opens = [{}];", opens.join(", ")).unwrap();
        let txs_lit: Vec<String> = w
            .txs
            .iter()
            .map(|t| {
                format!(
                    "TxWitness {{\n        from_pk_x: {}, from_pk_y: {}, from_index: {}, from_cash: {}, from_coll: {}, from_nonce: {},\n        from_siblings: {},\n        to_field: {}, to_index: {}, to_cash: {}, to_coll: {}, to_nonce: {},\n        to_siblings: {},\n        asset: {}, amount: {}, is_withdraw: {}, is_active: {},\n        sig: {},\n    }}",
                    to_hex(&t.from_pk_x), to_hex(&t.from_pk_y), t.from_index, t.from_cash, t.from_coll, t.from_nonce,
                    sibs(&t.from_siblings),
                    to_hex(&t.to_field), t.to_index, to_hex(&t.to_cash_or_leaf), t.to_coll, t.to_nonce,
                    sibs(&t.to_siblings),
                    t.asset as u32, t.amount, t.is_withdraw as u8, t.is_active as u8, sig_lit(&t.sig)
                )
            })
            .collect();
        writeln!(out, "    let txs = [{}];", txs_lit.join(", ")).unwrap();
        writeln!(out, "    (pis, roots, deps, opens, txs)\n}}\n").unwrap();
    }

    // --- Adversarial open fixtures over a funded 2-account state ---
    // Each returns (acct_root, pos_root, OpenWitness); all constraints hold
    // EXCEPT the named guard.
    let funded_state = || {
        let mut s = L2State::new();
        s.accounts.set(0, Account { pk_x: lender.pk_x(), cash: 10_000_000, coll: 0, nonce: 0 });
        s.accounts.set(1, Account { pk_x: borrower.pk_x(), cash: 0, coll: 5_000_000, nonce: 0 });
        s
    };

    // Helper to hand-build an OpenWitness against a state without mutating it.
    let manual_entry = |state: &L2State, p: &Position, req: &OpenRequest, pos_index: u32, pos_old_leaf: Fr| -> OpenEntry {
        let b_idx = state.accounts.find(&p.borrower_pk_x).unwrap();
        let l_idx = state.accounts.find(&p.lender_pk_x).unwrap();
        let b = state.accounts.get(b_idx).cloned().unwrap();
        let l = state.accounts.get(l_idx).cloned().unwrap();
        let (b_sibs, _) = state.accounts.path(&hasher, b_idx);
        // Lender witness must be against the POST-borrower-update tree.
        let mut mid = L2State {
            accounts: crate::tree::Tree { leaves: state.accounts.leaves.clone() },
            positions: PosTree { slots: state.positions.slots.clone() },
        };
        mid.accounts.set(b_idx, Account {
            pk_x: p.borrower_pk_x,
            cash: b.cash + p.cash,
            coll: b.coll.wrapping_sub(p.coll),
            nonce: b.nonce + 1,
        });
        let (l_sibs, _) = mid.accounts.path(&hasher, l_idx);
        let pos_sibs = state.positions.path(&hasher, pos_index);
        OpenEntry {
            borrower_pk_x: p.borrower_pk_x,
            borrower_pk_y: req.borrower_pk_y,
            borrower_index: b_idx,
            borrower_cash: b.cash,
            borrower_coll: b.coll,
            borrower_nonce: req.borrower_nonce,
            borrower_siblings: b_sibs,
            lender_pk_x: p.lender_pk_x,
            lender_pk_y: req.lender_pk_y,
            lender_index: l_idx,
            lender_cash: l.cash,
            lender_coll: l.coll,
            lender_nonce: req.lender_nonce,
            lender_siblings: l_sibs,
            cash: p.cash,
            coll: p.coll,
            rate_bps: p.rate_bps,
            haircut_bps: p.haircut_bps,
            open_ts: p.open_ts,
            maturity_ts: p.maturity_ts,
            pos_index,
            pos_old_leaf,
            pos_siblings: pos_sibs,
            borrower_sig: req.borrower_sig.clone(),
            lender_sig: req.lender_sig.clone(),
            is_active: true,
        }
    };

    // (1) Single signature: lender countersign missing (borrower's sig in
    // both slots). Everything else valid.
    {
        let state = funded_state();
        let p = demo_position(&borrower, &lender);
        let mut req = signed_open(&hasher, &p, &borrower, &lender, 0, 0, 3101, 3102);
        req.lender_sig = req.borrower_sig.clone();
        let e = manual_entry(&state, &p, &req, 0, FR_ZERO);
        writeln!(out, "/// Open with the borrower's signature in BOTH slots (lender never").unwrap();
        writeln!(out, "/// countersigned): only the lender signature check rejects.").unwrap();
        writeln!(
            out,
            "pub fn open_single_sig() -> (Field, Field, OpenWitness) {{\n    let w = {};\n    ({}, {}, w)\n}}\n",
            open_lit(&e),
            to_hex(&state.accounts.root(&hasher)),
            to_hex(&state.positions.root(&hasher)),
        )
        .unwrap();
    }

    // (2) Occupied slot: slot 0 already holds a position; witness honestly
    // carries its leaf (inclusion passes) — only the emptiness guard rejects.
    {
        let mut state = funded_state();
        let existing = Position {
            borrower_pk_x: borrower.pk_x(),
            lender_pk_x: lender.pk_x(),
            cash: 7,
            coll: 8,
            rate_bps: 1,
            haircut_bps: 1,
            open_ts: 1,
            maturity_ts: 2,
        };
        state.positions.set(0, existing.clone());
        let p = demo_position(&borrower, &lender);
        let req = signed_open(&hasher, &p, &borrower, &lender, 0, 0, 3201, 3202);
        let e = manual_entry(&state, &p, &req, 0, pos_leaf(&hasher, &existing));
        writeln!(out, "/// Open targeting an OCCUPIED slot with an honest inclusion proof of the").unwrap();
        writeln!(out, "/// existing leaf: only the pos_old_leaf == 0 guard rejects.").unwrap();
        writeln!(
            out,
            "pub fn open_occupied_slot() -> (Field, Field, OpenWitness) {{\n    let w = {};\n    ({}, {}, w)\n}}\n",
            open_lit(&e),
            to_hex(&state.accounts.root(&hasher)),
            to_hex(&state.positions.root(&hasher)),
        )
        .unwrap();
    }

    // (3) Lender cash overdraft: cash amount exceeds lender balance; both
    // signatures valid, only the u64 range check on the debit rejects.
    {
        let state = funded_state();
        let mut p = demo_position(&borrower, &lender);
        p.cash = 20_000_000; // lender has 10_000_000
        let req = signed_open(&hasher, &p, &borrower, &lender, 0, 0, 3301, 3302);
        let e = manual_entry(&state, &p, &req, 0, FR_ZERO);
        writeln!(out, "/// Open whose cash leg exceeds the lender's balance (signed by both!):").unwrap();
        writeln!(out, "/// only the 64-bit range check on the lender debit rejects.").unwrap();
        writeln!(
            out,
            "pub fn open_lender_overdraft() -> (Field, Field, OpenWitness) {{\n    let w = {};\n    ({}, {}, w)\n}}\n",
            open_lit(&e),
            to_hex(&state.accounts.root(&hasher)),
            to_hex(&state.positions.root(&hasher)),
        )
        .unwrap();
    }

    // (4) Borrower coll overdraft.
    {
        let state = funded_state();
        let mut p = demo_position(&borrower, &lender);
        p.coll = 6_000_000; // borrower has 5_000_000
        let req = signed_open(&hasher, &p, &borrower, &lender, 0, 0, 3401, 3402);
        let e = manual_entry(&state, &p, &req, 0, FR_ZERO);
        writeln!(out, "/// Open whose coll leg exceeds the borrower's balance: only the 64-bit").unwrap();
        writeln!(out, "/// range check on the collateral debit rejects.").unwrap();
        writeln!(
            out,
            "pub fn open_coll_overdraft() -> (Field, Field, OpenWitness) {{\n    let w = {};\n    ({}, {}, w)\n}}\n",
            open_lit(&e),
            to_hex(&state.accounts.root(&hasher)),
            to_hex(&state.positions.root(&hasher)),
        )
        .unwrap();
    }

    // (5) Unsigned term mutation: signatures cover 430 bps; witness claims
    // 999 bps. Only the signature binding of term_hash rejects.
    {
        let state = funded_state();
        let p = demo_position(&borrower, &lender);
        let req = signed_open(&hasher, &p, &borrower, &lender, 0, 0, 3501, 3502);
        let mut p2 = p.clone();
        p2.rate_bps = 999;
        let e = manual_entry(&state, &p2, &req, 0, FR_ZERO);
        writeln!(out, "/// Witness rate_bps differs from the signed terms: the in-circuit").unwrap();
        writeln!(out, "/// open message diverges and both signature checks fail.").unwrap();
        writeln!(
            out,
            "pub fn open_terms_not_signed() -> (Field, Field, OpenWitness) {{\n    let w = {};\n    ({}, {}, w)\n}}\n",
            open_lit(&e),
            to_hex(&state.accounts.root(&hasher)),
            to_hex(&state.positions.root(&hasher)),
        )
        .unwrap();
    }

    // (6) Inactive (padding) open over a state with one live position:
    // identity on both trees.
    {
        let mut state = funded_state();
        state.positions.set(0, demo_position(&borrower, &lender));
        let entry = {
            // Reuse the builder's padding shape via a zero-slot manual pad.
            let slot0 = state.accounts.get(0).cloned().unwrap();
            let (acct_sibs, _) = state.accounts.path(&hasher, 0);
            let pos_old_leaf = PosTree::leaf_value(&hasher, state.positions.get(0));
            let pos_sibs = state.positions.path(&hasher, 0);
            let pad_sig = crate::keys::pad_signature(&hasher);
            OpenEntry {
                borrower_pk_x: slot0.pk_x,
                borrower_pk_y: FR_ZERO,
                borrower_index: 0,
                borrower_cash: slot0.cash,
                borrower_coll: slot0.coll,
                borrower_nonce: slot0.nonce,
                borrower_siblings: acct_sibs,
                lender_pk_x: slot0.pk_x,
                lender_pk_y: FR_ZERO,
                lender_index: 0,
                lender_cash: slot0.cash,
                lender_coll: slot0.coll,
                lender_nonce: slot0.nonce,
                lender_siblings: acct_sibs,
                cash: 0,
                coll: 0,
                rate_bps: 0,
                haircut_bps: 0,
                open_ts: 0,
                maturity_ts: 0,
                pos_index: 0,
                pos_old_leaf,
                pos_siblings: pos_sibs,
                borrower_sig: pad_sig.clone(),
                lender_sig: pad_sig,
                is_active: false,
            }
        };
        writeln!(out, "/// Inactive (padding) open over a state with a live position at slot 0:").unwrap();
        writeln!(out, "/// apply_open must leave both roots and the DA accumulator unchanged.").unwrap();
        writeln!(
            out,
            "pub fn open_inactive() -> (Field, Field, OpenWitness) {{\n    let w = {};\n    ({}, {}, w)\n}}\n",
            open_lit(&entry),
            to_hex(&state.accounts.root(&hasher)),
            to_hex(&state.positions.root(&hasher)),
        )
        .unwrap();
    }

    out
}
