#!/usr/bin/env bash
# Deploy guard (issue #2): refuse to ship an image whose circuit VK the
# target contract can never verify. The rollup VK is contract-immutable, so
# a circuit-changing merge must go through an explicit re-bootstrap
# (scripts/bootstrap_testnet.sh), never an ordinary deploy.
#
# Usage: scripts/check_vk.sh CONTRACT_ID [RPC_URL [NETWORK_PASSPHRASE]]
#   RPC_URL / passphrase default to Stellar testnet.
#
# Requires nargo + bb on PATH (same pinned versions as the Dockerfile) and,
# for the on-chain comparison, the stellar CLI. If the live contract predates
# the vk_hash() getter, the guard falls back to comparing against the
# checked-in fixtures/batch_repo/vk.bin (regenerated by nightly, so drift is
# caught within a day).
set -euo pipefail
cd "$(dirname "$0")/.."

CIRCUIT="${CIRCUIT_PKG:-batch_repo}"
CONTRACT_ID="${1:?usage: scripts/check_vk.sh CONTRACT_ID [RPC_URL [NETWORK_PASSPHRASE]]}"
RPC_URL="${2:-https://soroban-testnet.stellar.org}"
PASSPHRASE="${3:-Test SDF Network ; September 2015}"

echo "==> compiling $CIRCUIT and exporting its verification key"
( cd circuits && nargo compile --package "$CIRCUIT" >/dev/null \
  && bb write_vk --scheme ultra_honk --oracle_hash keccak \
       --bytecode_path "target/${CIRCUIT}.json" --output_path "target/${CIRCUIT}-vk" >/dev/null )
VK_BIN="circuits/target/${CIRCUIT}-vk/vk"

sha() { shasum -a 256 "$1" 2>/dev/null | cut -d' ' -f1 || sha256sum "$1" | cut -d' ' -f1; }
IMAGE_VK_HASH=$(sha "$VK_BIN")
echo "    image VK sha256: $IMAGE_VK_HASH"

echo "==> reading vk_hash() from contract $CONTRACT_ID"
if CHAIN_HASH=$(stellar contract invoke --id "$CONTRACT_ID" \
      --rpc-url "$RPC_URL" --network-passphrase "$PASSPHRASE" \
      --send=no -- vk_hash 2>/dev/null); then
  CHAIN_HASH=$(echo "$CHAIN_HASH" | tr -d '"' | tr '[:upper:]' '[:lower:]')
  echo "    chain VK sha256: $CHAIN_HASH"
  if [ "$CHAIN_HASH" != "$IMAGE_VK_HASH" ]; then
    echo "::error::VK MISMATCH: this image's $CIRCUIT VK does not match contract $CONTRACT_ID."
    echo "A circuit/VK change requires the re-bootstrap workflow (scripts/bootstrap_testnet.sh),"
    echo "updating the deployment's contract ids, and an on-chain proof smoke test — not an ordinary deploy."
    exit 1
  fi
  echo "OK: image VK matches the live contract."
else
  echo "    contract has no vk_hash() getter (pre-#2 deployment); falling back to fixture compare"
  FIXTURE_HASH=$(sha "fixtures/$CIRCUIT/vk.bin")
  echo "    fixture VK sha256: $FIXTURE_HASH"
  if [ "$FIXTURE_HASH" != "$IMAGE_VK_HASH" ]; then
    echo "::error::VK MISMATCH: current circuits produce a different VK than fixtures/$CIRCUIT/vk.bin."
    echo "The live contract was bootstrapped from the fixture-era circuits; deploying this image"
    echo "would ship a prover the contract cannot verify. Use the re-bootstrap workflow."
    exit 1
  fi
  echo "OK: image VK matches the checked-in production fixture."
fi
